apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
spec:
  encryptedData:
    dummykey1: AgCXNkgGbetYCyQnmQ/7lfNoS270Tlhu07NiUsxQLmrlJK6w4U+YeVLnZqewcZEDGghc1/PVMlkeBL8YKcP1YuOMDezn02wnj/GCGFppugitOCsPdAkZMdMboelNpCm1wnPmLOXTbJ2fxY/VIQ/9fnhJWA2DJJNRslVIfl10epCzdYd4SKXcxtRjCkGgrgUsOck1hLqgArcFcYF8QoZsO7g/ViYGy0lMxvz/bXsNAUhzaH70O1+VgDsLZrTFQOgDHneYVp9YLPg7pv8iM2JNxy3s7jUMdFfotFmFsyp2KviHogLjDyukqsbm4hfQgPMyxbcIddU0cxJljaTP/1POe3Mj+T8Rm3hP8mEjTMCOE4/QwkLVI6Lp1yKRyNiQmtS8TC+aT+Idokp5UXFZ3pLb2HB2DfldGhcQGNRjt6Esm1O+D+ZDoPs+VR1V4cUGWnBYQFdXLQ/DY52DhF4bv4fH67biYTIdzhi/977ShOwzDZxbrKkYUjdtF9yVYjEj05Hlj9Ux6Up69YBUwKCIkyvikHFDE+qJdcru/h05b4PK5M8V3IxZMa/7QU/mlYIHFak34XSl6eSzE95VSubUOXR6BcAoXu24/7dqPFAfhih4xdjVixvpd28GAPODeokIRxI/8uhG6PTSZ4BQP50yNKOEwRxqnnprbpLpdsJYVv3s4uUeVeaCDoJ2tCFwp13rZ6soiDyeczAS9E+Xdw3H8w==
    dummykey2: AgCKJ4ctjGrkjd1My8+pQaJw6iWGPBgvkl4PahVuKRceKM/eKQMJpIJ8NJX9V25IFA6DLAHHHZv4VfgNQsHxV+EYtzYviTQvOKYuqmN1mbgpMg0e3EmkQLf4lhCFDl4XonloRBJd2FdaGfk/q0Gfy0/PLuT08LF+Efxd/uPc9GfZWG0nXoqoV/EOdzYKaHLhZonB2BzhxzfSwsOOdt5N2FiM3l7mEv/FtlONCnk7IoSbIH5/F1wzGOtPIOerPfBuZitsn0h0ePFRZghCMDjyFGtTPfXOOry8CdpJXw02Kt3MXJmt+VlL9ZMcWPBwNKxe3b+y+/BZrAV8yBBcVUxyAFtwpPygBJdd2LomC3kL2OhJibNNxucOnXcH9TxzxbnsLRbn63IR4JMd5fkyPqS3qgu47uS32U4zxvz8S0ViowLoFvA8kHH59EGjGW8RzmYcCowdgDX0IPCzOuAQY3mvIDBdYHfaTx52JQJJNSuzXPiS4Mh67x9PqqfseZwRisdFdPlvScQtb26xCuw0cM7UV2kk9crIXk/YXZ0hVkNYOAoyuZaR9mcADTkxIynuXUa/yOp4Ixaao4wKQUI+ntwaj6tpMoqoyOpTrBFeyTPJuks4DFCOiaXdS7HKs0OuWEMb5luicag7ksgUv+VVfSsGpEu04yCQHFGaXRtL1zpYmnxopvx68J+2+2jIYla8jf7Dqx6A0spz2uEHGdI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: my-secret
