apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
spec:
  encryptedData:
    dummykey1: AgB6wEw0f69BJl62jbJ1YAd19mEKqom4SVhyJbP82J5BBfXvj2YzuKCOqndPzrV1/RtCkWsPRESbx8f2FFj9X4y6rKALN4O4IlMWNdxes2kMaNpcEaEhPO8+PV2nBn5inJ8V5KhYOObezhuXRCFAuLeiwrbZKI83BqrHSqlrLFQIWtnEMwbMyD6GsIhGgJicYBMH3+BS8XwhQnyl8i+3jcL1w06s4jfMN8a8KVeDvcRinU1yzayBYn0Awbp7MlEJNRLFn/C2/f/zhb9LKy4OK9ZbufjYHVtfYo4/18mMXiL7bhBk5VeSS/e70T524aY6LOct5Yi0kN9eUgv3Sms5A47aGEyUOJNhJ55PWG2Kb8OY48M1y7g4SklfKBQi2yKDazOhZxsAQCAAj2zgjpq6Oqkqcr/PleZxXdqHCUPGtULthJlemgc+sgBpWMBh4XhEkGW9PRxS0ntOwwZyNZk6c95hjegrz9sWL6l2QVNXk5/xCeQ906eS1KsvvBQbwG+MO4Cv9Dkp2czF7KCxdpI3cv5DGMv2oPU4quT7/Pm1hiiDa+G8hgDODeJchZvObpiFCQPtibgckti6bwEFQGOfZRJdyppF2FFM/gOECIdSJsro+5fR6deIqjRyyfdeIKK2foll4J5UKLvMY3jEVqYSmSZ4kjrefMMDXDSft9GRrIAnO5glIbSXSNHjJ7pJkEGdp2/HQJ5QIXikarAOVg==
    dummykey2: AgA5vo8vdRGpAy79rfZE1hdUe6WPRGYD48ht2hXRyAFF02eqpDK1EjHOfc/sbBu15pX0cQhyIDbI6yIFSR4eeiL2Je1gmVD1bHu4HfCZXD1SaztDELXRe9ePHkk718VVuSy0vNqcq9jYFcvXEQeoVICT343zRFc0yDCiG3g4onp/EKVkg5csShOus++Uu3jR8i55C69T+EP9y6k1Y+fVooiTj98MPeelzYOCzDkWASJs8Sqxh4Q1rZW+bn2cvPgOQG9ArNUTF2MUKRyssJRgCC+gKM42liJUXCFvkG93f1k4XQxzzGMviPS55TeBsBKOuCblTvZkK/0jMo81ODZWt8a4exfPU1JKOlrQo4q1sYwARDBdyQhdIOX29fpYu4Ccwsk0FKLGg65YLMx2UGkCfUQBugNSZeUXWxQvv2f/LSpS9e2F8x1YDzH1Ee87Pzr5yHY8JlC4PmNOD+msKDY94hhv2PLqpdybvhXZnfqBVWNT6hPsC7NMWPGjPblZ9FiVt+3/D2N6+n40alzBkeUgeFJdDgmwpyZ1e1UnrUKziqaVw/7Pn+X5hE5uUa5VoIu+fi1+JpsMWqehdt6vx02WpezMTe4sjp7WC9ktb4zT0uBJZJDJwsjRKr4Q7WjeF8Q2AwgE8+LaZvjKdOzJdDbdWfAs+DId6z7KcjV9hH5ALzg1P4DahKml8qoabD6ZPygzjbBeBtWIpo8RQGA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: my-secret

